# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cud_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CUD_UI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.cud_title_line = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cud_title_line.sizePolicy().hasHeightForWidth())
        self.cud_title_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.cud_title_line.setFont(font)
        self.cud_title_line.setAlignment(QtCore.Qt.AlignCenter)
        self.cud_title_line.setObjectName("cud_title_line")
        self.verticalLayout_2.addWidget(self.cud_title_line)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.cud_content_plain = QtWidgets.QPlainTextEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cud_content_plain.setFont(font)
        self.cud_content_plain.setObjectName("cud_content_plain")
        self.verticalLayout_3.addWidget(self.cud_content_plain)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cud_confirm_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cud_confirm_button.sizePolicy().hasHeightForWidth())
        self.cud_confirm_button.setSizePolicy(sizePolicy)
        self.cud_confirm_button.setMinimumSize(QtCore.QSize(300, 100))
        self.cud_confirm_button.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.cud_confirm_button.setFont(font)
        self.cud_confirm_button.setStyleSheet("#cud_confirm_button {\n"
                                              "    background: transparent;\n"
                                              "    font: \"Comic Sans MS\";\n"
                                              "    font-size: 30pt;\n"
                                              "}\n"
                                              "\n"
                                              "#cud_confirm_button:pressed {\n"
                                              "    background: transparent;\n"
                                              "    font: \"Comic Sans MS\";\n"
                                              "    font-size: 28pt;\n"
                                              "}")
        self.cud_confirm_button.setObjectName("cud_confirm_button")
        self.horizontalLayout_3.addWidget(self.cud_confirm_button, 0, QtCore.Qt.AlignRight)
        self.cud_quit_button = QtWidgets.QPushButton(Form)
        self.cud_quit_button.setMinimumSize(QtCore.QSize(300, 100))
        self.cud_quit_button.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cud_quit_button.setFont(font)
        self.cud_quit_button.setStyleSheet("#cud_quit_button {\n"
                                           "    background: transparent;\n"
                                           "    font: \"Comic Sans MS\";\n"
                                           "    font-size: 30pt;\n"
                                           "}\n"
                                           "\n"
                                           "#cud_quit_button:pressed {\n"
                                           "    background: transparent;\n"
                                           "    font: \"Comic Sans MS\";\n"
                                           "    font-size: 28pt;\n"
                                           "}")
        self.cud_quit_button.setObjectName("cud_quit_button")
        self.horizontalLayout_3.addWidget(self.cud_quit_button, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название уровня"))
        self.label_2.setText(_translate("Form", "Текст уровня"))
        self.cud_confirm_button.setText(_translate("Form", "Сохранить"))
        self.cud_quit_button.setText(_translate("Form", "Отмена"))
