# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Custom_UI(object):
    def setupUi(self, custom_menu):
        custom_menu.setObjectName("custom_menu")
        custom_menu.resize(1200, 800)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(custom_menu)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.custom_logo = QtWidgets.QLabel(custom_menu)
        self.custom_logo.setMinimumSize(QtCore.QSize(600, 300))
        self.custom_logo.setMaximumSize(QtCore.QSize(650, 325))
        self.custom_logo.setStyleSheet("#custom_logo {\n"
                                       "background-color: transparent;\n"
                                       "border-image:url(:/images/images/custom_logo.png);\n"
                                       "background: none;\n"
                                       "border: none;\n"
                                       "background-repeat: none;\n"
                                       "}\n"
                                       "")
        self.custom_logo.setText("")
        self.custom_logo.setObjectName("custom_logo")
        self.verticalLayout_7.addWidget(self.custom_logo, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.buttons_layout = QtWidgets.QVBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.verticalLayout_7.addLayout(self.buttons_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_level_button = QtWidgets.QPushButton(custom_menu)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_level_button.setFont(font)
        self.add_level_button.setStyleSheet("#add_level_button {\n"
                                            "    background: transparent;\n"
                                            "    font: \"Comic Sans MS\";\n"
                                            "    font-size: 30pt;\n"
                                            "}\n"
                                            "\n"
                                            "#add_level_button:pressed {\n"
                                            "    background: transparent;\n"
                                            "    font: \"Comic Sans MS\";\n"
                                            "    font-size: 28pt;\n"
                                            "}")
        self.add_level_button.setObjectName("add_level_button")
        self.horizontalLayout_2.addWidget(self.add_level_button)
        self.update_level_button = QtWidgets.QPushButton(custom_menu)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.update_level_button.setFont(font)
        self.update_level_button.setStyleSheet("#update_level_button {\n"
                                               "    background: transparent;\n"
                                               "    font: \"Comic Sans MS\";\n"
                                               "    font-size: 30pt;\n"
                                               "}\n"
                                               "\n"
                                               "#update_level_button:pressed {\n"
                                               "    background: transparent;\n"
                                               "    font: \"Comic Sans MS\";\n"
                                               "    font-size: 28pt;\n"
                                               "}")
        self.update_level_button.setObjectName("update_level_button")
        self.horizontalLayout_2.addWidget(self.update_level_button)
        self.delete_level_button = QtWidgets.QPushButton(custom_menu)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.delete_level_button.setFont(font)
        self.delete_level_button.setStyleSheet("#delete_level_button {\n"
                                               "    background: transparent;\n"
                                               "    font: \"Comic Sans MS\";\n"
                                               "    font-size: 30pt;\n"
                                               "}\n"
                                               "\n"
                                               "#delete_level_button:pressed {\n"
                                               "    background: transparent;\n"
                                               "    font: \"Comic Sans MS\";\n"
                                               "    font-size: 28pt;\n"
                                               "}")
        self.delete_level_button.setObjectName("delete_level_button")
        self.horizontalLayout_2.addWidget(self.delete_level_button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.custom_quit_button = QtWidgets.QPushButton(custom_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_quit_button.sizePolicy().hasHeightForWidth())
        self.custom_quit_button.setSizePolicy(sizePolicy)
        self.custom_quit_button.setMinimumSize(QtCore.QSize(100, 100))
        self.custom_quit_button.setMaximumSize(QtCore.QSize(100, 100))
        self.custom_quit_button.setStyleSheet("#custom_quit_button {\n"
                                              "background-color: transparent;\n"
                                              "border-image: url(:/icons/images/widget_quit.png);\n"
                                              "background: none;\n"
                                              "border: none;\n"
                                              "background-repeat: none;\n"
                                              "}\n"
                                              "#custom_quit_button:pressed\n"
                                              "{\n"
                                              "   border-image: url(:/icons/images/widget_quit_clicked.png);\n"
                                              "}")
        self.custom_quit_button.setText("")
        self.custom_quit_button.setObjectName("custom_quit_button")
        self.verticalLayout_8.addWidget(self.custom_quit_button, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 7)
        self.horizontalLayout_3.setStretch(2, 1)

        self.retranslateUi(custom_menu)
        QtCore.QMetaObject.connectSlotsByName(custom_menu)

    def retranslateUi(self, custom_menu):
        _translate = QtCore.QCoreApplication.translate
        custom_menu.setWindowTitle(_translate("custom_menu", "Кастомные уровни"))
        self.add_level_button.setText(_translate("custom_menu", "Добавить"))
        self.update_level_button.setText(_translate("custom_menu", "Изменить"))
        self.delete_level_button.setText(_translate("custom_menu", "Удалить"))
        self.custom_quit_button.setShortcut(_translate("custom_menu", "Esc"))
