# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Game_UI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1210, 794)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.keyboard_hide_button = QtWidgets.QPushButton(Form)
        self.keyboard_hide_button.setMinimumSize(QtCore.QSize(100, 100))
        self.keyboard_hide_button.setMaximumSize(QtCore.QSize(100, 100))
        self.keyboard_hide_button.setStyleSheet("#keyboard_hide_button {\n"
                                                "    background-color: transparent;\n"
                                                "    border-image: url(:/icons/images/keyboard_on.png);\n"
                                                "    background: none;\n"
                                                "    border: none;\n"
                                                "    background-repeat: none;\n"
                                                "}")
        self.keyboard_hide_button.setText("")
        self.keyboard_hide_button.setObjectName("keyboard_hide_button")
        self.verticalLayout.addWidget(self.keyboard_hide_button)
        self.hands_hide_button = QtWidgets.QPushButton(Form)
        self.hands_hide_button.setMinimumSize(QtCore.QSize(100, 100))
        self.hands_hide_button.setMaximumSize(QtCore.QSize(100, 100))
        self.hands_hide_button.setStyleSheet("#hands_hide_button {\n"
                                             "    background-color: transparent;\n"
                                             "    border-image: url(:/icons/images/hands_on.png);\n"
                                             "    background: none;\n"
                                             "    border: none;\n"
                                             "    background-repeat: none;\n"
                                             "}")
        self.hands_hide_button.setText("")
        self.hands_hide_button.setObjectName("hands_hide_button")
        self.verticalLayout.addWidget(self.hands_hide_button, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.central_layout = QtWidgets.QVBoxLayout()
        self.central_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.central_layout.setContentsMargins(-1, 5, 0, 10)
        self.central_layout.setSpacing(0)
        self.central_layout.setObjectName("central_layout")
        self.timer_label = QtWidgets.QLabel(Form)
        self.timer_label.setMaximumSize(QtCore.QSize(1000, 200))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.timer_label.setFont(font)
        self.timer_label.setText("")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.central_layout.addWidget(self.timer_label, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.displayed_text = DisplayText(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayed_text.sizePolicy().hasHeightForWidth())
        self.displayed_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.displayed_text.setFont(font)
        self.displayed_text.setText("")
        self.displayed_text.setAlignment(QtCore.Qt.AlignCenter)
        self.displayed_text.setReadOnly(True)
        self.displayed_text.setObjectName("displayed_text")
        self.central_layout.addWidget(self.displayed_text)
        self.progress_bar = QtWidgets.QProgressBar(Form)
        self.progress_bar.setMaximumSize(QtCore.QSize(1530, 50))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.central_layout.addWidget(self.progress_bar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_hand_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_hand_label.sizePolicy().hasHeightForWidth())
        self.left_hand_label.setSizePolicy(sizePolicy)
        self.left_hand_label.setMinimumSize(QtCore.QSize(100, 100))
        self.left_hand_label.setMaximumSize(QtCore.QSize(250, 250))
        self.left_hand_label.setStyleSheet("#left_hand_label {\n"
                                           "    background-color: transparent;\n"
                                           "    border-image:url(:/images/images/left_hand.png);\n"
                                           "    background: none;\n"
                                           "    border: none;\n"
                                           "    background-repeat: none;\n"
                                           "}\n"
                                           "")
        self.left_hand_label.setText("")
        self.left_hand_label.setObjectName("left_hand_label")
        self.horizontalLayout_4.addWidget(self.left_hand_label)
        self.keyboard_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboard_label.sizePolicy().hasHeightForWidth())
        self.keyboard_label.setSizePolicy(sizePolicy)
        self.keyboard_label.setMinimumSize(QtCore.QSize(500, 150))
        self.keyboard_label.setMaximumSize(QtCore.QSize(1620, 550))
        self.keyboard_label.setStyleSheet("#keyboard_label {\n"
                                          "    background-color: transparent;\n"
                                          "    border-image:url(:/images/images/keyboard.png);\n"
                                          "    background: none;\n"
                                          "    border: none;\n"
                                          "    background-repeat: none;\n"
                                          "    opacity: 0;\n"
                                          "}\n"
                                          "")
        self.keyboard_label.setText("")
        self.keyboard_label.setObjectName("keyboard_label")
        self.horizontalLayout_4.addWidget(self.keyboard_label)
        self.right_hand_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_hand_label.sizePolicy().hasHeightForWidth())
        self.right_hand_label.setSizePolicy(sizePolicy)
        self.right_hand_label.setMinimumSize(QtCore.QSize(100, 100))
        self.right_hand_label.setMaximumSize(QtCore.QSize(250, 250))
        self.right_hand_label.setStyleSheet("#right_hand_label {\n"
                                            "    background-color: transparent;\n"
                                            "    border-image: url(:/images/images/right_hand.png);\n"
                                            "    background: none;\n"
                                            "    border: none;\n"
                                            "    background-repeat: none;\n"
                                            "}\n"
                                            "")
        self.right_hand_label.setText("")
        self.right_hand_label.setObjectName("right_hand_label")
        self.horizontalLayout_4.addWidget(self.right_hand_label)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.central_layout.addLayout(self.horizontalLayout_4)
        self.input_text_line = TypingFilter(Form)
        self.input_text_line.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_text_line.sizePolicy().hasHeightForWidth())
        self.input_text_line.setSizePolicy(sizePolicy)
        self.input_text_line.setMinimumSize(QtCore.QSize(0, 0))
        self.input_text_line.setMaximumSize(QtCore.QSize(1500, 200))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(35)
        self.input_text_line.setFont(font)
        self.input_text_line.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.input_text_line.setAcceptDrops(False)
        self.input_text_line.setStyleSheet("#input_text_line {\n"
                                           "\n"
                                           "}")
        self.input_text_line.setInputMask("")
        self.input_text_line.setText("")
        self.input_text_line.setAlignment(QtCore.Qt.AlignCenter)
        self.input_text_line.setClearButtonEnabled(False)
        self.input_text_line.setObjectName("input_text_line")
        self.central_layout.addWidget(self.input_text_line)
        self.central_layout.setStretch(1, 2)
        self.central_layout.setStretch(2, 1)
        self.central_layout.setStretch(3, 2)
        self.central_layout.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.central_layout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.game_quit_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_quit_button.sizePolicy().hasHeightForWidth())
        self.game_quit_button.setSizePolicy(sizePolicy)
        self.game_quit_button.setMinimumSize(QtCore.QSize(100, 100))
        self.game_quit_button.setMaximumSize(QtCore.QSize(100, 100))
        self.game_quit_button.setStyleSheet("#game_quit_button {\n"
                                            "background-color: transparent;\n"
                                            "border-image: url(:/icons/images/widget_quit.png);\n"
                                            "background: none;\n"
                                            "border: none;\n"
                                            "background-repeat: none;\n"
                                            "}\n"
                                            "#game_quit_button:pressed\n"
                                            "{\n"
                                            "   border-image: url(:/icons/images/widget_quit_clicked.png);\n"
                                            "}")
        self.game_quit_button.setText("")
        self.game_quit_button.setObjectName("game_quit_button")
        self.verticalLayout_5.addWidget(self.game_quit_button, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.setStretch(0, 7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Слепопечать v0.1"))
        self.input_text_line.setPlaceholderText(_translate("Form", "Печатать сюда"))
        self.game_quit_button.setShortcut(_translate("Form", "Esc"))


from src.widgets.DisplayTextWidget import DisplayText
from src.widgets.TypingFilterWidget import TypingFilter
