# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Main_UI(object):
    def setupUi(self, main_menu):
        main_menu.setObjectName("main_menu")
        main_menu.resize(1200, 835)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_menu.sizePolicy().hasHeightForWidth())
        main_menu.setSizePolicy(sizePolicy)
        main_menu.setMaximumSize(QtCore.QSize(1920, 1080))
        main_menu.setStyleSheet("#main_menu {\n"
                                "    background-color: transparent;\n"
                                "    background: none;\n"
                                "    border: none;\n"
                                "    background-repeat: none;\n"
                                "}\n"
                                "")
        self.horizontalLayout = QtWidgets.QHBoxLayout(main_menu)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_logo = QtWidgets.QLabel(main_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_logo.sizePolicy().hasHeightForWidth())
        self.main_logo.setSizePolicy(sizePolicy)
        self.main_logo.setMinimumSize(QtCore.QSize(600, 300))
        self.main_logo.setMaximumSize(QtCore.QSize(650, 325))
        self.main_logo.setStyleSheet("#main_logo {\n"
                                     "background-color: transparent;\n"
                                     "border-image:url(:/images/images/big_logo.png);\n"
                                     "background: none;\n"
                                     "border: none;\n"
                                     "background-repeat: none;\n"
                                     "}\n"
                                     "")
        self.main_logo.setText("")
        self.main_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.main_logo.setObjectName("main_logo")
        self.verticalLayout.addWidget(self.main_logo, 0, QtCore.Qt.AlignHCenter)
        self.startgame_button = QtWidgets.QPushButton(main_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startgame_button.sizePolicy().hasHeightForWidth())
        self.startgame_button.setSizePolicy(sizePolicy)
        self.startgame_button.setMinimumSize(QtCore.QSize(325, 75))
        self.startgame_button.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.startgame_button.setFont(font)
        self.startgame_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.startgame_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startgame_button.setStyleSheet("#startgame_button {\n"
                                            "    background: transparent;\n"
                                            "    font: \"Comic Sans MS\";\n"
                                            "    font-size: 30pt;\n"
                                            "}\n"
                                            "\n"
                                            "#startgame_button:pressed {\n"
                                            "    background: transparent;\n"
                                            "    font: \"Comic Sans MS\";\n"
                                            "    font-size: 28pt;\n"
                                            "}")
        self.startgame_button.setObjectName("startgame_button")
        self.verticalLayout.addWidget(self.startgame_button, 0, QtCore.Qt.AlignHCenter)
        self.record_button = QtWidgets.QPushButton(main_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_button.sizePolicy().hasHeightForWidth())
        self.record_button.setSizePolicy(sizePolicy)
        self.record_button.setMinimumSize(QtCore.QSize(325, 75))
        self.record_button.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.record_button.setFont(font)
        self.record_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.record_button.setStyleSheet("#record_button {\n"
                                         "    background: transparent;\n"
                                         "    font: \"Comic Sans MS\";\n"
                                         "    font-size: 30pt;\n"
                                         "}\n"
                                         "\n"
                                         "#record_button:pressed {\n"
                                         "    background: transparent;\n"
                                         "    font: \"Comic Sans MS\";\n"
                                         "    font-size: 28pt;\n"
                                         "}")
        self.record_button.setFlat(False)
        self.record_button.setObjectName("record_button")
        self.verticalLayout.addWidget(self.record_button, 0, QtCore.Qt.AlignHCenter)
        self.quit_button = QtWidgets.QPushButton(main_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_button.sizePolicy().hasHeightForWidth())
        self.quit_button.setSizePolicy(sizePolicy)
        self.quit_button.setMinimumSize(QtCore.QSize(325, 75))
        self.quit_button.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.quit_button.setFont(font)
        self.quit_button.setStyleSheet("#quit_button {\n"
                                       "    background: transparent;\n"
                                       "    font: \"Comic Sans MS\";\n"
                                       "    font-size: 30pt;\n"
                                       "}\n"
                                       "\n"
                                       "#quit_button:pressed {\n"
                                       "    background: transparent;\n"
                                       "    font: \"Comic Sans MS\";\n"
                                       "    font-size: 28pt;\n"
                                       "}")
        self.quit_button.setObjectName("quit_button")
        self.verticalLayout.addWidget(self.quit_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings_button = QtWidgets.QPushButton(main_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_button.sizePolicy().hasHeightForWidth())
        self.settings_button.setSizePolicy(sizePolicy)
        self.settings_button.setMinimumSize(QtCore.QSize(100, 100))
        self.settings_button.setMaximumSize(QtCore.QSize(100, 100))
        self.settings_button.setStyleSheet("#settings_button {\n"
                                           "background-color: transparent;\n"
                                           "border-image: url(:/icons/images/settings.png);\n"
                                           "background: none;\n"
                                           "border: none;\n"
                                           "background-repeat: none;\n"
                                           "}\n"
                                           "#settings_button:pressed\n"
                                           "{\n"
                                           "   border-image: url(:/icons/images/settings_clicked.png);\n"
                                           "}")
        self.settings_button.setText("")
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout_3.addWidget(self.settings_button, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(main_menu)
        QtCore.QMetaObject.connectSlotsByName(main_menu)

    def retranslateUi(self, main_menu):
        _translate = QtCore.QCoreApplication.translate
        main_menu.setWindowTitle(_translate("main_menu", "Слепопечать v0.1"))
        self.startgame_button.setText(_translate("main_menu", "Начать игру"))
        self.record_button.setText(_translate("main_menu", "Рекорды"))
        self.quit_button.setText(_translate("main_menu", "Выход"))
        self.settings_button.setShortcut(_translate("main_menu", "Esc"))
