# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pregame_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PreGame_UI(object):
    def setupUi(self, pregame_menu):
        pregame_menu.setObjectName("pregame_menu")
        pregame_menu.resize(1206, 800)
        pregame_menu.setMaximumSize(QtCore.QSize(1920, 1080))
        pregame_menu.setStyleSheet("#game_menu {\n"
                                   "    background-color: transparent;\n"
                                   "    background: none;\n"
                                   "    border: none;\n"
                                   "    background-repeat: none;\n"
                                   "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(pregame_menu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.main_layout.setContentsMargins(-1, 30, 0, 25)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.pregame_logo = QtWidgets.QLabel(pregame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pregame_logo.sizePolicy().hasHeightForWidth())
        self.pregame_logo.setSizePolicy(sizePolicy)
        self.pregame_logo.setMinimumSize(QtCore.QSize(600, 250))
        self.pregame_logo.setMaximumSize(QtCore.QSize(650, 300))
        self.pregame_logo.setStyleSheet("#pregame_logo {\n"
                                        "background-color: transparent;\n"
                                        "border-image: url(:/images/images/pregame_logo.png);\n"
                                        "background: none;\n"
                                        "border: none;\n"
                                        "background-repeat: none;\n"
                                        "}\n"
                                        "")
        self.pregame_logo.setText("")
        self.pregame_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.pregame_logo.setObjectName("pregame_logo")
        self.main_layout.addWidget(self.pregame_logo, 0, QtCore.Qt.AlignHCenter)
        self.buttons_layout = QtWidgets.QVBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.main_layout.addLayout(self.buttons_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_label = QtWidgets.QLabel(pregame_menu)
        self.name_label.setMinimumSize(QtCore.QSize(350, 85))
        self.name_label.setMaximumSize(QtCore.QSize(350, 110))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(23)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setWordWrap(True)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_2.addWidget(self.name_label)
        self.lang_label = QtWidgets.QLabel(pregame_menu)
        self.lang_label.setMinimumSize(QtCore.QSize(350, 75))
        self.lang_label.setMaximumSize(QtCore.QSize(350, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(23)
        self.lang_label.setFont(font)
        self.lang_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lang_label.setWordWrap(True)
        self.lang_label.setObjectName("lang_label")
        self.horizontalLayout_2.addWidget(self.lang_label)
        self.level_label = QtWidgets.QLabel(pregame_menu)
        self.level_label.setMinimumSize(QtCore.QSize(350, 75))
        self.level_label.setMaximumSize(QtCore.QSize(350, 110))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(23)
        self.level_label.setFont(font)
        self.level_label.setAlignment(QtCore.Qt.AlignCenter)
        self.level_label.setWordWrap(True)
        self.level_label.setObjectName("level_label")
        self.horizontalLayout_2.addWidget(self.level_label)
        self.main_layout.addLayout(self.horizontalLayout_2)
        self.startgame_button = QtWidgets.QPushButton(pregame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startgame_button.sizePolicy().hasHeightForWidth())
        self.startgame_button.setSizePolicy(sizePolicy)
        self.startgame_button.setMinimumSize(QtCore.QSize(325, 75))
        self.startgame_button.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.startgame_button.setFont(font)
        self.startgame_button.setStyleSheet("#startgame_button {\n"
                                            "    background: transparent;\n"
                                            "    font: \"Comic Sans MS\";\n"
                                            "    font-size: 30pt;\n"
                                            "}\n"
                                            "\n"
                                            "#startgame_button:pressed {\n"
                                            "    font: \"Comic Sans MS\";\n"
                                            "    font-size: 28pt;\n"
                                            "}")
        self.startgame_button.setObjectName("startgame_button")
        self.main_layout.addWidget(self.startgame_button, 0, QtCore.Qt.AlignHCenter)
        self.main_layout.setStretch(0, 3)
        self.main_layout.setStretch(1, 1)
        self.main_layout.setStretch(2, 1)
        self.main_layout.setStretch(3, 3)
        self.horizontalLayout.addLayout(self.main_layout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pregame_quit_button = QtWidgets.QPushButton(pregame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pregame_quit_button.sizePolicy().hasHeightForWidth())
        self.pregame_quit_button.setSizePolicy(sizePolicy)
        self.pregame_quit_button.setMinimumSize(QtCore.QSize(100, 100))
        self.pregame_quit_button.setMaximumSize(QtCore.QSize(100, 100))
        self.pregame_quit_button.setStyleSheet("#pregame_quit_button {\n"
                                               "background-color: transparent;\n"
                                               "border-image: url(:/icons/images/widget_quit.png);\n"
                                               "background: none;\n"
                                               "border: none;\n"
                                               "background-repeat: none;\n"
                                               "}\n"
                                               "#pregame_quit_button:pressed\n"
                                               "{\n"
                                               "   border-image: url(:/icons/images/widget_quit_clicked.png);\n"
                                               "}")
        self.pregame_quit_button.setText("")
        self.pregame_quit_button.setObjectName("pregame_quit_button")
        self.verticalLayout_5.addWidget(self.pregame_quit_button, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(pregame_menu)
        QtCore.QMetaObject.connectSlotsByName(pregame_menu)

    def retranslateUi(self, pregame_menu):
        _translate = QtCore.QCoreApplication.translate
        pregame_menu.setWindowTitle(_translate("pregame_menu", "Слепопечать v0.1"))
        self.name_label.setText(_translate("pregame_menu", "Ваше имя: KIRILL"))
        self.lang_label.setText(_translate("pregame_menu", "Язык текста: RU"))
        self.level_label.setText(_translate("pregame_menu", "Уровень: ва ол"))
        self.startgame_button.setText(_translate("pregame_menu", "Вперёд!"))
        self.pregame_quit_button.setShortcut(_translate("pregame_menu", "Esc"))
