# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Record_UI(object):
    def setupUi(self, top_menu):
        top_menu.setObjectName("top_menu")
        top_menu.resize(1200, 766)
        top_menu.setMaximumSize(QtCore.QSize(1920, 1080))
        top_menu.setStyleSheet("#top_menu {\n"
                               "    background-color: transparent;\n"
                               "    background: none;\n"
                               "    border: none;\n"
                               "    background-repeat: none;\n"
                               "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(top_menu)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.record_logo = QtWidgets.QLabel(top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_logo.sizePolicy().hasHeightForWidth())
        self.record_logo.setSizePolicy(sizePolicy)
        self.record_logo.setMinimumSize(QtCore.QSize(600, 200))
        self.record_logo.setMaximumSize(QtCore.QSize(650, 250))
        self.record_logo.setStyleSheet("#record_logo {\n"
                                       "background-color: transparent;\n"
                                       "border-image: url(:/images/images/top_logo.png);\n"
                                       "background: none;\n"
                                       "border: none;\n"
                                       "background-repeat: none;\n"
                                       "}\n"
                                       "")
        self.record_logo.setText("")
        self.record_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.record_logo.setObjectName("record_logo")
        self.verticalLayout.addWidget(self.record_logo, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.record_words_button = QtWidgets.QPushButton(top_menu)
        self.record_words_button.setMinimumSize(QtCore.QSize(100, 100))
        self.record_words_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.record_words_button.setFont(font)
        self.record_words_button.setStyleSheet("#record_words_button {\n"
                                               "    background: transparent;\n"
                                               "    font: \"Comic Sans MS\";\n"
                                               "    font-size: 20pt;\n"
                                               "}\n"
                                               "\n"
                                               "#record_words_button:pressed {\n"
                                               "    background: transparent;\n"
                                               "    font: \"Comic Sans MS\";\n"
                                               "    font-size: 18pt;\n"
                                               "}")
        self.record_words_button.setObjectName("record_words_button")
        self.horizontalLayout_2.addWidget(self.record_words_button)
        self.record_nums_button = QtWidgets.QPushButton(top_menu)
        self.record_nums_button.setMinimumSize(QtCore.QSize(100, 100))
        self.record_nums_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.record_nums_button.setFont(font)
        self.record_nums_button.setStyleSheet("#record_nums_button {\n"
                                              "    background: transparent;\n"
                                              "    font: \"Comic Sans MS\";\n"
                                              "    font-size: 20pt;\n"
                                              "}\n"
                                              "\n"
                                              "#record_nums_button:pressed {\n"
                                              "    background: transparent;\n"
                                              "    font: \"Comic Sans MS\";\n"
                                              "    font-size: 18pt;\n"
                                              "}")
        self.record_nums_button.setObjectName("record_nums_button")
        self.horizontalLayout_2.addWidget(self.record_nums_button)
        self.record_letters_button = QtWidgets.QPushButton(top_menu)
        self.record_letters_button.setMinimumSize(QtCore.QSize(100, 100))
        self.record_letters_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.record_letters_button.setFont(font)
        self.record_letters_button.setStyleSheet("#record_letters_button {\n"
                                                 "    background: transparent;\n"
                                                 "    font: \"Comic Sans MS\";\n"
                                                 "    font-size: 20pt;\n"
                                                 "}\n"
                                                 "\n"
                                                 "#record_letters_button:pressed {\n"
                                                 "    background: transparent;\n"
                                                 "    font: \"Comic Sans MS\";\n"
                                                 "    font-size: 18pt;\n"
                                                 "}")
        self.record_letters_button.setObjectName("record_letters_button")
        self.horizontalLayout_2.addWidget(self.record_letters_button)
        self.record_customs_button = QtWidgets.QPushButton(top_menu)
        self.record_customs_button.setMinimumSize(QtCore.QSize(120, 100))
        self.record_customs_button.setMaximumSize(QtCore.QSize(120, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.record_customs_button.setFont(font)
        self.record_customs_button.setStyleSheet("#record_customs_button {\n"
                                                 "    background: transparent;\n"
                                                 "    font: \"Comic Sans MS\";\n"
                                                 "    font-size: 20pt;\n"
                                                 "}\n"
                                                 "\n"
                                                 "#record_customs_button:pressed {\n"
                                                 "    background: transparent;\n"
                                                 "    font: \"Comic Sans MS\";\n"
                                                 "    font-size: 18pt;\n"
                                                 "}")
        self.record_customs_button.setObjectName("record_customs_button")
        self.horizontalLayout_2.addWidget(self.record_customs_button)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.record_table = QtWidgets.QTableWidget(top_menu)
        self.record_table.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.record_table.setFont(font)
        self.record_table.setAutoFillBackground(False)
        self.record_table.setLineWidth(5)
        self.record_table.setMidLineWidth(5)
        self.record_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.record_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.record_table.setShowGrid(True)
        self.record_table.setGridStyle(QtCore.Qt.SolidLine)
        self.record_table.setRowCount(0)
        self.record_table.setColumnCount(0)
        self.record_table.setObjectName("record_table")
        self.verticalLayout.addWidget(self.record_table)
        self.record_info_label = QtWidgets.QLabel(top_menu)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.record_info_label.setFont(font)
        self.record_info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.record_info_label.setObjectName("record_info_label")
        self.verticalLayout.addWidget(self.record_info_label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.record_quit_button = QtWidgets.QPushButton(top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_quit_button.sizePolicy().hasHeightForWidth())
        self.record_quit_button.setSizePolicy(sizePolicy)
        self.record_quit_button.setMinimumSize(QtCore.QSize(100, 100))
        self.record_quit_button.setMaximumSize(QtCore.QSize(100, 100))
        self.record_quit_button.setStyleSheet("#record_quit_button {\n"
                                              "background-color: transparent;\n"
                                              "border-image: url(:/icons/images/widget_quit.png);\n"
                                              "background: none;\n"
                                              "border: none;\n"
                                              "background-repeat: none;\n"
                                              "}\n"
                                              "#record_quit_button:pressed\n"
                                              "{\n"
                                              "   border-image: url(:/icons/images/widget_quit_clicked.png);\n"
                                              "}")
        self.record_quit_button.setText("")
        self.record_quit_button.setObjectName("record_quit_button")
        self.verticalLayout_3.addWidget(self.record_quit_button, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(top_menu)
        QtCore.QMetaObject.connectSlotsByName(top_menu)

    def retranslateUi(self, top_menu):
        _translate = QtCore.QCoreApplication.translate
        top_menu.setWindowTitle(_translate("top_menu", "Слепопечать v0.1"))
        self.record_words_button.setText(_translate("top_menu", "Слова"))
        self.record_nums_button.setText(_translate("top_menu", "Числа"))
        self.record_letters_button.setText(_translate("top_menu", "Буквы"))
        self.record_customs_button.setText(_translate("top_menu", "Кастом"))
        self.record_info_label.setText(_translate("top_menu", "Нажми на слово, чтобы отобразить рекорды категории"))
        self.record_quit_button.setShortcut(_translate("top_menu", "Esc"))
