# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Settings_UI(object):
    def setupUi(self, settings_menu):
        settings_menu.setObjectName("settings_menu")
        settings_menu.resize(1203, 800)
        settings_menu.setMaximumSize(QtCore.QSize(1920, 1080))
        settings_menu.setStyleSheet("#settings_menu {\n"
                                    "    background-color: transparent;\n"
                                    "    background: none;\n"
                                    "    border: none;\n"
                                    "    background-repeat: none;\n"
                                    "}\n"
                                    "")
        self.horizontalLayout = QtWidgets.QHBoxLayout(settings_menu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_logo = QtWidgets.QLabel(settings_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_logo.sizePolicy().hasHeightForWidth())
        self.settings_logo.setSizePolicy(sizePolicy)
        self.settings_logo.setMinimumSize(QtCore.QSize(600, 300))
        self.settings_logo.setMaximumSize(QtCore.QSize(650, 325))
        self.settings_logo.setStyleSheet("#settings_logo {\n"
                                         "background-color: transparent;\n"
                                         "border-image: url(:/images/images/settings_logo.png);\n"
                                         "background: none;\n"
                                         "border: none;\n"
                                         "background-repeat: none;\n"
                                         "}\n"
                                         "")
        self.settings_logo.setText("")
        self.settings_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_logo.setObjectName("settings_logo")
        self.verticalLayout.addWidget(self.settings_logo, 0, QtCore.Qt.AlignHCenter)
        self.changename_button = QtWidgets.QPushButton(settings_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changename_button.sizePolicy().hasHeightForWidth())
        self.changename_button.setSizePolicy(sizePolicy)
        self.changename_button.setMinimumSize(QtCore.QSize(325, 75))
        self.changename_button.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.changename_button.setFont(font)
        self.changename_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.changename_button.setStyleSheet("#changename_button {\n"
                                             "    background: transparent;\n"
                                             "    font: \"Comic Sans MS\";\n"
                                             "    font-size: 30pt;\n"
                                             "}\n"
                                             "\n"
                                             "#changename_button:pressed {\n"
                                             "    background: transparent;\n"
                                             "    font: \"Comic Sans MS\";\n"
                                             "    font-size: 28pt;\n"
                                             "}")
        self.changename_button.setObjectName("changename_button")
        self.verticalLayout.addWidget(self.changename_button, 0, QtCore.Qt.AlignHCenter)
        self.changebackground_button = QtWidgets.QPushButton(settings_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changebackground_button.sizePolicy().hasHeightForWidth())
        self.changebackground_button.setSizePolicy(sizePolicy)
        self.changebackground_button.setMinimumSize(QtCore.QSize(325, 75))
        self.changebackground_button.setMaximumSize(QtCore.QSize(325, 100))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(30)
        self.changebackground_button.setFont(font)
        self.changebackground_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.changebackground_button.setStyleSheet("#changebackground_button {\n"
                                                   "    background: transparent;\n"
                                                   "    font: \"Comic Sans MS\";\n"
                                                   "    font-size: 30pt;\n"
                                                   "}\n"
                                                   "\n"
                                                   "#changebackground_button:pressed {\n"
                                                   "    background: transparent;\n"
                                                   "    font: \"Comic Sans MS\";\n"
                                                   "    font-size: 28pt;\n"
                                                   "}")
        self.changebackground_button.setFlat(False)
        self.changebackground_button.setObjectName("changebackground_button")
        self.verticalLayout.addWidget(self.changebackground_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings_quit_button = QtWidgets.QPushButton(settings_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_quit_button.sizePolicy().hasHeightForWidth())
        self.settings_quit_button.setSizePolicy(sizePolicy)
        self.settings_quit_button.setMinimumSize(QtCore.QSize(100, 100))
        self.settings_quit_button.setMaximumSize(QtCore.QSize(100, 100))
        self.settings_quit_button.setStyleSheet("#settings_quit_button {\n"
                                                "background-color: transparent;\n"
                                                "border-image: url(:/icons/images/widget_quit.png);\n"
                                                "background: none;\n"
                                                "border: none;\n"
                                                "background-repeat: none;\n"
                                                "}\n"
                                                "#settings_quit_button:pressed\n"
                                                "{\n"
                                                "   border-image: url(:/icons/images/widget_quit_clicked.png);\n"
                                                "}")
        self.settings_quit_button.setText("")
        self.settings_quit_button.setObjectName("settings_quit_button")
        self.verticalLayout_3.addWidget(self.settings_quit_button, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 7)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(settings_menu)
        QtCore.QMetaObject.connectSlotsByName(settings_menu)

    def retranslateUi(self, settings_menu):
        _translate = QtCore.QCoreApplication.translate
        settings_menu.setWindowTitle(_translate("settings_menu", "Слепопечать v0.1"))
        self.changename_button.setText(_translate("settings_menu", "Сменить имя"))
        self.changebackground_button.setText(_translate("settings_menu", "Сменить фон"))
        self.settings_quit_button.setShortcut(_translate("settings_menu", "Esc"))
