english_levels = [
"dddjjj ddjdj jddjj djdjd jjdjd jd ddj djddj jdjdj ddjd jddj djd jdj jjd fffjjj ffjfj jffjj fjfjf jjfjf jdf fdj fjffj jfjfj jdjf dfj fjfj dfjd jdff kkkfff kkfkf fkkff kfkfk ffkfk dfk fjk kfkkf fkfkf jkdj djdk kjdk fkfj fdjk dddkkk ddkdk kddkk dkdkd kkdkd kfjd fdjk dkddk kdkdk fdkd jdjk kffj jffd kfjk dddfff ffdfd dffdd jdfd fkfd fdfdf ddfdf fddf dkff djdf kdfj jddf jjjkkk jjkjk kjjkk djkk djfj jkjkj kkjkj kdkf jdk jdfk dfkd ffjk fjfdk jdkkf jfjkd djffk dkdfj kfjjd kdkjf fkddj dkdd kjdf jddk fjkk jjkd ffdk fkkd jfjk kkfd jjfj",
"aaalll aalal laall alala llala dad all alaal lalal fall add fall add dad ssslll sslsl lssll slsls llsls fall sad slssl lslsl sad salad salad ask all ask ;;;sss ;;s;s s;;ss ;s;s; ss;s; sad; salad; ;s;;s s;s;s ask; salad; sad; ask; salad; aaa;;; aa;a; ;aa;; a;a;a ;;a;a all; fall; a;aa; ;a;a; add; all; ask; dad; fall; sad; aaasss ssasa assaa salad ask sasas aasas dad add all sad dad lll;;; ll;l; ;ll;; fall; all; l;l;l ;;l;l all; fall; salad; fall; all; slsa; la;;s lsl;a alss; a;asl ;slla ;a;ls s;aal sad salad; add dad; fall all ask; dad; sad all;",
"vvvnnn vvnvn nvvnn vnvnv nnvnv and dna vnvvn nvnvn and naval sand land fan bbbnnn bbnbn nbbnn bnbnb nnbnb ball van bnbbn nbnbn ban band bank bad lab mmmbbb mmbmb bmmbb mbmbm bbmbm blank mass mbmmb bmbmb mall band mad bad man vvvmmm vvmvm mvvmm vmvmv mmvmv van small vmvvm mvmvm slam naval van mask mass vvvbbb bbvbv vbbvv lab naval bvbvb vvbvb van naval ban ball bank nnnmmm nnmnm mnnmm sand mask nmnmn mmnmn dna blank slam land man small bnbvm nvmmb nbnmv vnbbm vmvbn mbnnv mvmnb bmvvn fan mall mad bad small man ban slam band lab",
"tttyyy ttyty yttyy tytyt yytyt nasty stay tytty ytyty may nafta stand any many gggyyy ggygy yggyy gygyg yygyg baby glass gyggy ygygy flag gas ally gym many hhhggg hhghg ghhgg hghgh gghgh half glad hghhg ghghg math bag hang shall gang ttthhh tthth htthh ththt hhtht flat hall thtth hthth that myth stab staff hat tttggg ggtgt tggtt fat batman gtgtg ttgtg tank gym fast thanks glass yyyhhh yyhyh hyyhh half day yhyhy hhyhy sky hand say fly shy gygth ythhg ygyht tyggh thtgy hgyyt hthyg ghtty lady daddy thank glass tall fantasy salt bat man talk blast badly",
"eeeuuu eeueu ueeuu eueue uueue gate busy eueeu ueueu level valuable bush legal budget rrruuu rruru urruu rurur uurur fun stare rurru ururu gut beer area usual emerge iiirrr iirir riirr iriri rriri final large iriir ririr very year dirt bridge birth eeeiii eeiei ieeii eieie iieie bit member eieei ieiei silent night several dismiss three eeerrr rrere erree seed barrier rerer eerer evil yard merger test drag uuuiii uuiui iuuii side rule uiuiu iiuiu build inside useful tire justify rurei ueiir uruie eurri eieru iruue ieiur rieeu ahead tube drunk seven sheet hide earth tribe birthday gear",
"qqqooo qqoqo oqqoo qoqoq ooqoq stone quality qoqqo oqoqo around adequate squad soil reason wwwooo wwowo owwoo wowow oowow somehow known wowwo owowo work favor reward sweet holder downtown pppwww ppwpw wppww pwpwp wwpwp paint wealthy pwppw wpwpw lip wisdom help how water qqqppp qqpqp pqqpp qpqpq ppqpq apple quite qpqqp pqpqp question pipe quote quarter pump qqqwww wwqwq qwwqq equal widow wqwqw qqwqw quest world powerful know square oooppp oopop poopp novel proper opopo ppopo outfit report proof photo primary wowqp oqppw owopq qowwp qpqwo pwooq pqpow wpqqo flower plane wine western simply hotel pool pride wrong unique mosque queen",
"xxx,,, xx,x, ,xx,, x,x,x ,,x,x fix, exam, x,xx, ,x,x, extra, anxious, mix, six, expert, ccc,,, cc,c, ,cc,, c,c,c ,,c,c excite, shock, c,cc, ,c,c, pack, vaccine, recipe, scary, touch, ...ccc ..c.c c..cc .c.c. cc.c. coffee. county. .c..c c.c.c chip. anchor. school. stick. cook. xxx... xx.x. .xx.. x.x.x ..x.x text. next. x.xx. .x.x. box. mixed. oxygen. explore. relax. xxxccc ccxcx xccxx twice expect cxcxc xxcxc excellent exist toxic cruise car ,,,... ,,.,. .,,.. execute, article. ,.,., ..,., become, experiment. coast, service, except. c,cx. ,x..c ,c,.x x,cc. x.xc, .c,,x .x.,c c.xx, expertise, exhibit. pitch. child, receive, exile. piece. excuse, victory, exact.",
"zzz??? zz?z? ?zz?? z?z?z ??z?z freeze? dozen? z?zz? ?z?z? crazy? zoo? citizen? pizza? seize? !!!??? !!?!? ?!!?? !?!?! ??!?! zero! analyze? !?!!? ?!?!? squeeze? prize! amazed! puzzle? magazine?! ///!!! //!/! !//!! /!/!/ !!/!/ size/zero! /!//! !/!/! amazing/organized/realize/organize! jazz! zzz/// zz/z/ /zz// z/z/z //z/z zero/freeze z/zz/ /z/z/ seize/magazine/bizarre/realize/size zzz!!! !!z!z z!!zz dozen! puzzle! !z!z! zz!z! emphasize! amazing! zoo! prize! squeeze! ???/// ??/?/ /??// amazed/analyze? ?/?/? //?/? crazy? pizza/zero/organize? horizon/citizen? !?!z/ ?z//! ?!?/z z?!!/ z/z!? /!??z /z/?! !/zz? puzzle/zoo? freeze! size! dozen? jazz! prize/crazy! pizza? amazed!",
]